import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Porky Oink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.nav}>
        <ol class="flex list-none justify-between px-4">
          <li class="p-4 mr-10"><a href="#">HOME</a></li>
          <li class="p-4 hover:bg-violet-400 active:bg-violet-600 focus:outline-none focus:ring focus:ring-violet-300"><a href="#">About</a></li>
          <li class="p-4 hover:bg-violet-400 active:bg-violet-600 focus:outline-none focus:ring focus:ring-violet-300"><a href="#">Roadmap</a></li>
          <li class="p-4 hover:bg-violet-400 active:bg-violet-600 focus:outline-none focus:ring focus:ring-violet-300"><a href="#">Team</a></li>
        </ol>
      </nav>

      <div class="h-2 bg-black"></div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Porky Oink</a>
        </h1>

        <h1 class="text-4xl pt-10">About</h1>
        <div className={styles.grid}>
          Fill this with about
        </div>

        <h1 class="text-4xl pt-10">Roadmap</h1>
        <div className={styles.grid}>
          Fill this with roadmap
        </div>

        <h1 class="text-4xl pt-10">Meet the team</h1>
        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <div>Image</div>
            <div>Name</div>
            <hr></hr>
            <p>Description</p>
          </a>

          <a href="#" className={styles.card}>
            <div>Image</div>
            <div>Name</div>
            <hr></hr>
            <p>Description</p>
          </a>

          <a href="#" className={styles.card}>
            <div>Image</div>
            <div>Name</div>
            <hr></hr>
            <p>Description</p>
          </a>

          <a href="#" className={styles.card}>
            <div>Image</div>
            <div>Name</div>
            <hr></hr>
            <p>Description</p>
          </a>
        </div>
      </main>

      <div class="h-2 bg-black"></div>

      <footer className={styles.footer}>
        <h1 class="text-left">Porky Oink 2022@</h1>
        <ol class="flex list-none justify-between mx-4">
          <li class="mx-4"><a href="#">Social</a></li>
          <li class="mx-4"><a href="#">Social</a></li>
          <li class="mx-4"><a href="#">Social</a></li>
        </ol>
      </footer>
    </div>
  )
}
